#!/usr/bin/python3
import sys
from math import isqrt

def is_prime(n, k=5):
    if n == 2 or n == 3:
        return True
    if n < 2 or n % 2 == 0:
        return False

    r, s = 0, n - 1
    while s % 2 == 0:
        r += 1
        s //= 2

    for _ in range(k):
        a = random.randint(2, n - 2)
        x = pow(a, s, n)

        if x == 1 or x == n - 1:
            continue

        for _ in range(r - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False

    return True

def factorize(number):
    for i in range(2, isqrt(number) + 1):
        if number % i == 0 and is_prime(i) and is_prime(number // i):
            return i, number // i
    return None, None

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    filename = sys.argv[1]
    try:
        with open(filename, 'r') as file:
            number = int(file.readline().strip())
            p, q = factorize(number)
            if p is not None:
                print(f"{number}={p}*{q}")
    except FileNotFoundError:
        print(f"File '{filename}' not found.")

if __name__ == '__main__':
    main()
